version: "2"

volumes:
  nginx:
  varnish:

services:
  nginx:
    image: nginx:1.13
    ports:
      - ${PORT_NGINX}:80
    volumes:
      - ./src/var/www/html:/usr/share/nginx/html:ro
      - ./src/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx:/var/log/nginx
    container_name: aggregate-miner-nginx
  varnish:
    image: million12/varnish:latest
    depends_on:
      - nginx
    links:
      - nginx:backend-host
    volumes:
      - ./src/etc/varnish/default.vcl:/etc/varnish/default.vcl:ro
      - ./src/etc/varnish/varnish.params:/etc/varnish/varnish.params:ro
      - varnish:/var/log/varnish
    ports:
      - ${PORT_VARNISH}:80
    container_name: aggregate-miner-varnish
    environment:
      VARNISHNCSA_ENABLED: 1